### ISSUE TITLE
Accept invitation page isn't styled.

### ISSUE THREAD

**Issue by yasinishyn** [lits-ruby-and-rails-course/geekometer#35]
Suggestion is to make the form look like login form.
https://www.dropbox.com/s/n1a3wvlk2772qoi/Screenshot%202015-07-24%2019.33.04.png?dl=0

**Comment by scarlet1986** [comment]
але через те, що сторінка підтвердження пароля для ще не залогіненого користувача, хедер виглядає не дуже)))
