### ISSUE TITLE
Logo icon must be a link to the root path.

### ISSUE THREAD

**Issue by yasinishyn** [lits-ruby-and-rails-course/geekometer#36]
https://www.dropbox.com/s/q4u2dci602ijjbt/Screenshot%202015-07-24%2019.34.37.png?dl=0

**Comment by EssenceMaks** [comment]
all work, but we need logo image

**Comment by EssenceMaks** [comment]
```
 змінював в роутах root 'users#show'  , була потреба  в "user id" 
```

я так розмію що була необхідність додати " get '/users/:id' => 'users#show' "  ??

 побачив що до логотипу в "_header.erb" необхідно було додати "   :title => "Back to Welcome Page"), root_path(current_user)  "
