### ISSUE TITLE
Add button 'pass the test' to the top menu.

### ISSUE THREAD

**Issue by yasinishyn** [lits-ruby-and-rails-course/geekometer#37]
To the centre of the navigation, add button 'pass the test ->'
Example:
https://www.dropbox.com/s/qxy8mrzv7prnq1v/Screenshot%202015-07-24%2019.37.14.png?dl=0

**Comment by EssenceMaks** [comment]
bootstrap не дає можливості встановити елемент по центру. перечитав документацію там нема таких можливостей, що дуже дивно. загуглив як це зробити, треба влізти в гем бутстрапу і вписати css налаштування. вирішив туди не лізти, бо не знайшов, і можу щось "наламати"
тому просто зробив блочний елемент, здається добре виглядає.

**Comment by EssenceMaks** [comment]
після того як Надя зробила доподаун кнопку, получився конфлікт з моїм пул ріквестом, тому що в нас робота над спільною "шапкою сайту" . після того як у Наді всі строчні елементи замінилися на один блочний, бутстрап не давав мені спокійно поставити ще один блочний елемен, він зносив один з блочних елементів на рівень нижче. і ще одна особливість бутстрапу він не дає можливості вирівняти якийсь з елементів "nav-bar" тобто шапки по центру. це його карма або зліва або справа. тому пішов на аферу і зробив особисті стилі, так як знайти файл бутстрапа зі стилями не зміг.(у майбутньому стилі можна перенести у той файл, коли він знайдеться падло)

**Comment by nadiyaka** [comment]
Я вже пофіксала весь header :) https://github.com/lits-ruby-and-rails-course/geekometer/pull/65
