### ISSUE TITLE
Сторінка "Створити питання для тесту"

### ISSUE THREAD

**Issue by kunik** [lits-ruby-and-rails-course/geekometer#5]
1. Тема (вибрати зі списку)
2. Саме питання
3. Варіанти відповіді (виберіть 1 з)
4. Складність питання
5. Правильний варіант відповіді

**Comment by kunik** [comment]
1. Саме питання
2. Варіанти відповіді (виберіть 1 з)

**Comment by bassment** [comment]
'Add new question' page created.

**Comment by scarlet1986** [comment]
крутоо!!! молодець!
